# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'brew_designv2.ui'
#
# Created by: PyQt5 UI code generator 5.12.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(577, 544)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout_7 = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout_7.setObjectName("gridLayout_7")
        self.pump_frame = QtWidgets.QFrame(self.centralwidget)
        self.pump_frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.pump_frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.pump_frame.setObjectName("pump_frame")
        self.gridLayout_6 = QtWidgets.QGridLayout(self.pump_frame)
        self.gridLayout_6.setObjectName("gridLayout_6")
        self.radio_pump_on = QtWidgets.QRadioButton(self.pump_frame)
        self.radio_pump_on.setObjectName("radio_pump_on")
        self.gridLayout_6.addWidget(self.radio_pump_on, 1, 0, 1, 1)
        self.pump_label = QtWidgets.QLabel(self.pump_frame)
        self.pump_label.setObjectName("pump_label")
        self.gridLayout_6.addWidget(self.pump_label, 0, 0, 1, 1)
        self.radio_pump_off = QtWidgets.QRadioButton(self.pump_frame)
        self.radio_pump_off.setObjectName("radio_pump_off")
        self.gridLayout_6.addWidget(self.radio_pump_off, 1, 3, 1, 1)
        self.gridLayout_7.addWidget(self.pump_frame, 1, 0, 1, 1)
        self.control_technique_frame = QtWidgets.QFrame(self.centralwidget)
        self.control_technique_frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.control_technique_frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.control_technique_frame.setObjectName("control_technique_frame")
        self.gridLayout_4 = QtWidgets.QGridLayout(self.control_technique_frame)
        self.gridLayout_4.setObjectName("gridLayout_4")
        self.control_technique_label = QtWidgets.QLabel(self.control_technique_frame)
        self.control_technique_label.setObjectName("control_technique_label")
        self.gridLayout_4.addWidget(self.control_technique_label, 0, 0, 1, 1)
        self.control_technique_dropdown = QtWidgets.QComboBox(self.control_technique_frame)
        self.control_technique_dropdown.setEditable(False)
        self.control_technique_dropdown.setObjectName("control_technique_dropdown")
        self.gridLayout_4.addWidget(self.control_technique_dropdown, 0, 1, 1, 1)
        self.gridLayout_7.addWidget(self.control_technique_frame, 1, 1, 1, 1)
        self.temperature_frame = QtWidgets.QFrame(self.centralwidget)
        self.temperature_frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.temperature_frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.temperature_frame.setObjectName("temperature_frame")
        self.gridLayout_5 = QtWidgets.QGridLayout(self.temperature_frame)
        self.gridLayout_5.setObjectName("gridLayout_5")
        self.temperature_current_setpoint_label = QtWidgets.QLabel(self.temperature_frame)
        self.temperature_current_setpoint_label.setObjectName("temperature_current_setpoint_label")
        self.gridLayout_5.addWidget(self.temperature_current_setpoint_label, 3, 0, 1, 2)
        self.temperature_measurement_lcd = QtWidgets.QLCDNumber(self.temperature_frame)
        self.temperature_measurement_lcd.setObjectName("temperature_measurement_lcd")
        self.gridLayout_5.addWidget(self.temperature_measurement_lcd, 4, 2, 1, 2)
        self.temperature_setpoint_label = QtWidgets.QLabel(self.temperature_frame)
        self.temperature_setpoint_label.setObjectName("temperature_setpoint_label")
        self.gridLayout_5.addWidget(self.temperature_setpoint_label, 2, 0, 1, 1)
        self.temperature_measurement_label = QtWidgets.QLabel(self.temperature_frame)
        self.temperature_measurement_label.setObjectName("temperature_measurement_label")
        self.gridLayout_5.addWidget(self.temperature_measurement_label, 4, 0, 1, 2)
        self.temperature_setpoint_lcd = QtWidgets.QLCDNumber(self.temperature_frame)
        self.temperature_setpoint_lcd.setObjectName("temperature_setpoint_lcd")
        self.gridLayout_5.addWidget(self.temperature_setpoint_lcd, 3, 2, 1, 2)
        self.line = QtWidgets.QFrame(self.temperature_frame)
        self.line.setFrameShape(QtWidgets.QFrame.HLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setObjectName("line")
        self.gridLayout_5.addWidget(self.line, 1, 0, 1, 4)
        self.temperature_label = QtWidgets.QLabel(self.temperature_frame)
        self.temperature_label.setObjectName("temperature_label")
        self.gridLayout_5.addWidget(self.temperature_label, 0, 0, 1, 1)
        self.temperature_setpoint_btn = QtWidgets.QPushButton(self.temperature_frame)
        self.temperature_setpoint_btn.setObjectName("temperature_setpoint_btn")
        self.gridLayout_5.addWidget(self.temperature_setpoint_btn, 2, 3, 1, 1)
        self.temperature_setpoint_spinbox = QtWidgets.QDoubleSpinBox(self.temperature_frame)
        self.temperature_setpoint_spinbox.setObjectName("temperature_setpoint_spinbox")
        self.gridLayout_5.addWidget(self.temperature_setpoint_spinbox, 2, 1, 1, 2)
        self.gridLayout_7.addWidget(self.temperature_frame, 0, 0, 1, 1)
        self.start_stop_frame = QtWidgets.QFrame(self.centralwidget)
        self.start_stop_frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.start_stop_frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.start_stop_frame.setObjectName("start_stop_frame")
        self.gridLayout = QtWidgets.QGridLayout(self.start_stop_frame)
        self.gridLayout.setObjectName("gridLayout")
        self.start_control_btn = QtWidgets.QPushButton(self.start_stop_frame)
        self.start_control_btn.setObjectName("start_control_btn")
        self.gridLayout.addWidget(self.start_control_btn, 0, 0, 1, 1)
        self.stop_control_btn = QtWidgets.QPushButton(self.start_stop_frame)
        self.stop_control_btn.setObjectName("stop_control_btn")
        self.gridLayout.addWidget(self.stop_control_btn, 0, 1, 1, 1)
        self.gridLayout_7.addWidget(self.start_stop_frame, 2, 0, 1, 2)
        self.history_frame = QtWidgets.QFrame(self.centralwidget)
        self.history_frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.history_frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.history_frame.setObjectName("history_frame")
        self.gridLayout_3 = QtWidgets.QGridLayout(self.history_frame)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.history_graphics = QtWidgets.QGraphicsView(self.history_frame)
        self.history_graphics.setObjectName("history_graphics")
        self.gridLayout_3.addWidget(self.history_graphics, 1, 0, 1, 1)
        self.history_label = QtWidgets.QLabel(self.history_frame)
        self.history_label.setObjectName("history_label")
        self.gridLayout_3.addWidget(self.history_label, 0, 0, 1, 1)
        self.gridLayout_7.addWidget(self.history_frame, 0, 1, 1, 1)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 577, 22))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Brewpi 5000"))
        self.radio_pump_on.setText(_translate("MainWindow", "På"))
        self.pump_label.setText(_translate("MainWindow", "Pumpe"))
        self.radio_pump_off.setText(_translate("MainWindow", "Av"))
        self.control_technique_label.setText(_translate("MainWindow", "Reguleringsteknikk"))
        self.temperature_current_setpoint_label.setText(_translate("MainWindow", "Nåværende setpoint"))
        self.temperature_setpoint_label.setText(_translate("MainWindow", "Setpoint"))
        self.temperature_measurement_label.setText(_translate("MainWindow", "Temperatur i kjele"))
        self.temperature_label.setText(_translate("MainWindow", "Temperatur"))
        self.temperature_setpoint_btn.setText(_translate("MainWindow", "Ok"))
        self.start_control_btn.setText(_translate("MainWindow", "Start regulering"))
        self.stop_control_btn.setText(_translate("MainWindow", "Stopp regulering"))
        self.history_label.setText(_translate("MainWindow", "Historikk"))




if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
